Added Swagger
renaudcalmont/aspnetcore-mongodb-sandbox pull request #1
Opened 2017-01-27 21:20 UTC by abauzac

Hello world :)))

Added swagger based on https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger#nuget-packages

2017-01-30 09:23 UTC, renaudcalmont requested changes

2017-01-30 09:23 UTC, renaudcalmont commented on src/Sandbox.Server.Http/Startup.cs
> +                c.SwaggerDoc("v1", new Info {
This swagger directive labels the generated documentation with "v1" but doesn't filter the matching API prefix.
See https://github.com/domaindrivendev/Swashbuckle/issues/392

2017-02-02 20:11 UTC, abauzac commented
Added predicate. Kind of working. I also found this net core project inside the Swagger repository : https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/WebSites/MultipleVersions but I think it may be "too far" for the current project (or not?)

2017-02-03 17:09 UTC, merged

2017-02-03 17:14 UTC, renaudcalmont commented
Thanks for the Swagger integration and comments. You're right about the website versioning, I think it is slightly out of the scope of this repository.